name: Build-Doc
on:
  push:
    branches:
      - main

jobs:
  build-doc:
    name: Build the documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
      - name: Install pdoc3
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            pdoc3
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            default: true
            override: true
            components: rustfmt, clippy
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - run: mkdir pages
      - run: mdbook build guide && mv guide/book pages/guide
      - run: cargo build && mv target/debug/libezel.so ezel.so && pdoc3 --force --html -o pdoc_pages ezel.so && mkdir pages/api && mv pdoc_pages/ezel.html pages/api/index.html
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
